### ISSUE TITLE
unrecognizable Coordinate Label

### ISSUE THREAD

**Issue by CySxL** [p-x9/ShowTouch#18]
When user invoke the second and further more touches, the Coordinate Labels oh them are unrecognizable 😂😂

Also it's kinda greedy for RAM(?
Not quite sure but I can observe the delay animation of the movement of dots.

![image](https://github.com/p-x9/ShowTouch/assets/15531137/cf2f732c-e729-4246-8b31-43ffe109ee8c)
The left dot is the first touch while the middle dot is the second touch and the right dot is the third touch.

**Comment by p-x9** [comment]
I was able to reproduce the problem too.

It seems to be caused by multiple layers of UIWindow on the home screen, etc.

I will fix it.

**Comment by p-x9** [comment]
https://github.com/p-x9/ShowTouch/releases/tag/0.3.1

**Comment by CySxL** [comment]
> https://github.com/p-x9/ShowTouch/releases/tag/0.3.1

Hmmm I installed it but now it's just now working at all 😂.


Neither enabling it in preference nor via cc toggle. The dot just doesn't show up.

**Comment by p-x9** [comment]
@CySxL 
Just updated the binary on the release page

**Comment by CySxL** [comment]
Fixed! ![image](https://github.com/p-x9/ShowTouch/assets/15531137/6b336c61-2617-4b6f-9cc8-5087538ee583)
